name: Build PDF version and deploy to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Use these Python versions
        python: [
          3.11.1,     # Current latest Python
        ]
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Homebrew dependencies
        run: |
          brew install weasyprint
      - name: Install font
        run: |
          brew tap homebrew/cask-fonts
          brew install --cask font-noto-serif-cjk
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Show Python version
        run: python --version
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build PDF
        run: |
          mkdocs build
      - name: Rename and Move PDF
        run: |
          mkdir pdf
          mv site/en/pdf/document.pdf pdf/${{ github.event.repository.name }}-en-${{ env.SHORT_SHA }}.pdf
          mv site/zh/pdf/document.pdf pdf/${{ github.event.repository.name }}-zh-${{ env.SHORT_SHA }}.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ env.SHORT_SHA }}-Generated-PDF
          path: pdf
      - name: Release PDF
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Generated PDF - ${{ github.event.repository.name }}-${{ env.SHORT_SHA }}"
          files: |
            pdf/${{ github.event.repository.name }}-en-${{ env.SHORT_SHA }}.pdf
            pdf/${{ github.event.repository.name }}-zh-${{ env.SHORT_SHA }}.pdf
          automatic_release_tag: "Generated-PDF-${{ github.event.repository.name }}-${{ env.SHORT_SHA }}"
          prerelease: false
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force